### ISSUE TITLE
register translation

### ISSUE THREAD

**Issue by Yamakaky** [lefticus/6502-cpp#3]
How do you manage the translation of the registers? I assume there are less registers on 6502 than on x86.

**Comment by boblaublaw** [comment]
In his talk I believe @lefticus  mentions that the leftover registers are assigned some fixed addresses in the [zero page](https://en.wikipedia.org/wiki/Zero_page) which the 6502 will access faster than other RAM.

**Comment by Yamakaky** [comment]
Oh, right. But how can we be sure that the program doesn't use it?

**Comment by lefticus** [comment]
That is correct. I use zero page mapping of x86 registers. The mapping is here: https://github.com/lefticus/x86-to-6502/blob/master/src/main.cpp#L75-L92

I'm relying on two things specifically
1. I'm targeting the C64, so I know that the ROM/hardware isn't using those locations: http://sta.c64.org/cbm64mem.html
2. I'm assuming that the entire program executing is the one that was translated from x86

**Comment by Yamakaky** [comment]
Ok, thank.

**Comment by boblaublaw** [comment]
How best to implement alternative zero-page mappings?  Implement `get_register` as a function pointer and write multiple implementations?  Make new `C64` and `A2` classes that inherit from a the base `6502` class and implement their own `get_register` methods?

I'm specifically thinking of targeting Apple II.

http://apple2.org.za/gswv/a2zine/faqs/csa2pfaq.html#017

**Comment by lefticus** [comment]
Since this is just a huge experiment anyhow and I have no idea what would be the best answer in the long run - I say go with the function pointer (or std::function, or template Callable thing?) and we'll see how it ends up working out.
