### ISSUE TITLE
Any idea if this re-assembler idea can be used with Z80 instead of 6502

### ISSUE THREAD

**Issue by codeorcode** [lefticus/6502-cpp#6]
Hi,

Using the same technology would it be possible to write in C++ and then translate the assembler to Z80 cpus ? Of course re-writing x86-to-6502 project. I want to know if it is possible and how hard would it be for someone who does not know assembler language at all (but wants to learn it).

Thank you very much for this and for your youtube videos. Sorry if this is the wrong place to post, I did not know a better place.

best regards,
ovi

**Comment by lefticus** [comment]
Yes, there's another project working on that: https://github.com/janwilmans/x86-to-z80

I don't know any z80, but I would suggest looking at that project.

Glad you like the youtube videos!

re: @janwilmans
